curl -X POST "https://accounts.spotify.com/api/token" \
      >  -H "Content-Type: application/x-www-form-urlencoded" \
      >  -d "grant_type=client_credentials&client_id=78a4f4ce43c5466e8c26cb6c73f0cfb4&client_secret=c42c0521910d45c1bc1a094467a4614c"

{
   "access_token": "BQAlRLMA989uTB-T92RzQDRVU3IYRC2Mh8z46u5VO_AtPxy7J--2X1VWZhptUdEpCKfJokg-w4AJ008Q1ExaUiLh8woPBth3YMZgzdFKXXasEM7tAIdb",
   "token_type": "Bearer",
   "expires_in": 3600
}



curl "https://api.spotify.com/v1/artists/4Z8W4fKeB5YxbusRsdQVPb" \
      >  -H "Authorization: Bearer  BQDBKJ5eo5jxbtpWjVOj7ryS84khybFpP_lTqzV7uV-T_m0cTfwvdn5BnBSKPxKgEb11"
