CREATE TABLE Person (
   Id INT UNSIGNED NOT NULL,
   Title VARCHAR(255) DEFAULT NULL,
   Artist VARCHAR(255) DEFAULT NULL,
   Album VARCHAR(255) DEFAULT NULL,
   TrackNum SMALLINT DEFAULT NULL,
   PRIMARY KEY (Id)
);